version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-codedeploy
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 300
      runas: ubuntu
      
